const URL = 'https://25.javascript.pages.academy/keksobooking'
const RERENDER_DELAY = 500
const MAX_PRICE = 100000
const MIN_PRICE = 1000
const OFFERS_COUNT = 10
const MIDDLE_PRICE = 50000
const LOW_PRICE = 10000
const START_ADDRESS_AVATAR = 'img/muffin-grey.svg'
const ALERT_SHOW_TIME = 5000
export { URL, MAX_PRICE, MIN_PRICE, OFFERS_COUNT, MIDDLE_PRICE, LOW_PRICE, START_ADDRESS_AVATAR, ALERT_SHOW_TIME, RERENDER_DELAY }
